using System;
using System.Collections.Generic;
using System.IO;
using Newtonsoft.Json.Linq;
using UnityEngine;

namespace Safehouse.Data
{
    /// <summary>A data file was missing, unreadable, or not the shape the rules expect.</summary>
    public sealed class GameDataException : Exception
    {
        public GameDataException(string message) : base(message) { }
        public GameDataException(string message, Exception inner) : base(message, inner) { }
    }

    /// <summary>Names of the JSON documents under StreamingAssets/data, without the extension.</summary>
    public static class GameDataFile
    {
        // Generated by the Python tools/import_tarkov.py - never hand-edit these.
        public const string Items = "items";
        public const string Traders = "traders";
        public const string Maps = "maps";
        public const string Gear = "gear";

        // Values we decided ourselves; these are meant to be hand-tuned.
        public const string Containers = "containers";
        public const string Combat = "combat";
        public const string RaidNodes = "raid_nodes";
        public const string MapsOverrides = "maps_overrides";

        public static readonly IReadOnlyList<string> All = new[]
        {
            Items, Traders, Maps, Gear, Containers, Combat, RaidNodes, MapsOverrides,
        };
    }

    /// <summary>
    /// Reads the game's reference data. The C# counterpart of the Python side's
    /// storage.prepare_environment: it only locates, reads and version-checks the documents.
    /// Turning them into typed rules is each module's own job (catalog, gear, maps, raids).
    /// </summary>
    public static class GameDataLoader
    {
        /// <summary>
        /// Every data/*.json carries this version. When the format changes, write a converter and
        /// bump this instead of letting a differently-shaped file load and fail somewhere deeper.
        /// </summary>
        public const int SupportedSchemaVersion = 1;

        /// <summary>
        /// StreamingAssets, not Resources: these files ship next to the built game as plain,
        /// hand-editable JSON, exactly like the Python build's data/ folder. Resources would bake
        /// them into the player and take away that property.
        /// </summary>
        public static string RootPath => Path.Combine(Application.streamingAssetsPath, "data");

        public static string PathFor(string name) => Path.Combine(RootPath, name + ".json");

        public static JObject Load(string name)
        {
            var path = PathFor(name);
            if (!File.Exists(path))
            {
                throw new GameDataException($"Data file is missing: {path}");
            }

            JObject document;
            try
            {
                document = JObject.Parse(File.ReadAllText(path));
            }
            catch (Exception error)
            {
                throw new GameDataException($"Data file is not valid JSON: {path}", error);
            }

            var version = document["schema_version"];
            if (version == null || version.Type != JTokenType.Integer)
            {
                throw new GameDataException($"Data file has no integer schema_version: {path}");
            }

            var found = version.Value<int>();
            if (found != SupportedSchemaVersion)
            {
                throw new GameDataException(
                    $"Data file schema_version is {found}, expected {SupportedSchemaVersion}: {path}");
            }

            return document;
        }

        public static Dictionary<string, JObject> LoadAll()
        {
            var documents = new Dictionary<string, JObject>(GameDataFile.All.Count);
            foreach (var name in GameDataFile.All)
            {
                documents[name] = Load(name);
            }

            return documents;
        }
    }
}
